# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=9.99, max_digits=100),
        ),
    ]
