# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 07:14
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20170609_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/Users/bach/Desktop/python/myvirtualenv/digitalmarket/static_cdn/protected'), upload_to=products.models.download_media_location),
        ),
    ]
